/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import LocalConfig from "./LocalConfig";
import GameStart from "./GameStart";

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;

    }
}
GameConfig.width = 450;
GameConfig.height = 800;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "horizontal";
GameConfig.alignV = "center";
GameConfig.alignH = "center";
GameConfig.startScene = "";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
